// This file is generated by the openedx/frontend-platform's "intl-import.js" script.
//
// Refer to the i18n documents in https://docs.openedx.org/en/latest/developers/references/i18n.html to update
// the file and use the Micro-frontend i18n pattern in new repositories.
//

import messagesOfArLanguage from './ar.json';
import messagesOfEs419Language from './es_419.json';
import messagesOfFrCaLanguage from './fr_CA.json';
import messagesOfPtBrLanguage from './pt_BR.json';
import messagesOfRuLanguage from './ru.json';
import messagesOfZhCnLanguage from './zh_CN.json';

export default {
  'ar': messagesOfArLanguage,
  'zh-cn': messagesOfZhCnLanguage,
  'ru': messagesOfRuLanguage,
  'pt-br': messagesOfPtBrLanguage,
  'fr-ca': messagesOfFrCaLanguage,
  'es-419': messagesOfEs419Language,
};
